spring:
  cloud:
    stream:
      function:
        bindings:
          consumerOrder-in-0: order-todo
      bindings:
        order-todo:
          group: main
    function:
      definition: consumerOrder