server:
  port: 8080  #端口号
spring:
  application:
    name: pos-gateway
  cloud:
    gateway: #网关路由配置
      routes:
        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: products   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://POS-PRODUCTS          #匹配后提供服务的路由地址
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/products/**               #断言，路径匹配 注意：Path 中 P 为大写
            # - Method=GET #只能时 GET 请求时，才能访问
          filters:
            - PrefixPath=/products-api
            - name: CircuitBreaker
              args:
                name: productsCircuitBreaker
                fallbackUri: forward:/fallback

        - id: session-test
          uri: lb://POS-CART
          predicates:
            - Path=/session/**,/checkout/**,/cart/**
          filters:
            - PrefixPath=/cart-api
            - name: CircuitBreaker
              args:
                name: cartCircuitBreaker
                fallbackUri: forward:/fallback

#        - id: checkout
#          uri: lb://POS-CART
#          predicates:
#            - Path=/checkout/**
#          filters:
#            - PrefixPath=/cart-api
#            - name: CircuitBreaker
#              args:
#                name: cartCircuitBreaker
#                fallbackUri: forward:/fallback
#
#        - id: cart
#          uri: lb://POS-CART
#          predicates:
#            - Path=/cart/**
#          filters:
#            - PrefixPath=/cart-api
#            - name: CircuitBreaker
#              args:
#                name: cartCircuitBreaker
#                fallbackUri: forward:/fallback

        - id: delivery
          uri: lb://POS-DELIVERY
          predicates:
            - Path=/delivery/**,/delivery-sse/**
#            - Path=/delivery-sse/**
          filters:
            - PrefixPath=/delivery-api
            - name: CircuitBreaker
              args:
                name: deliveryCircuitBreaker
                fallbackUri: forward:/fallback

#        - id: delivery-si
#          uri: lb://POS-GATEWAY
#          predicates:
#            - Path=/si-api/check/*
#          filters:
##              - PrefixPath=/delivery-api
#            - name: CircuitBreaker
#              args:
#                name: deliveryCircuitBreaker
#                fallbackUri: forward:/fallback


eureka:
  instance:
    instance-id: pos-gateway-8080
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

